#!/home/cakers/Software/anaconda3/envs/onedrive-sync/bin/python
import CLICommands as cli
import logging
import sys

# App/Client ID: 9806a116-6f7d-4154-a06e-0c887dd51eed
# Tenant ID: 42a7cc42-d023-4e93-898d-3777ba423ebe

if __name__ == '__main__':
    logging.basicConfig()

    if sys.argv[1] == 'init':
        cli.Init().execute()

    if not cli.IsInit().execute():
        print('initialisation has not been run, please run "ods init" first')
        sys.exit(1)

    match(sys.argv[1]):
        case 'cd':
            cli.Cd(sys.argv).execute()
        case 'ls':
            cli.Ls().execute()
        case 'pwd':
            cli.Pwd().execute()
        case 'get':
            try:
                cli.Get(sys.argv).execute()
            except:
                sys.exit(1)
        case 'put':
            try:
                cli.Put(sys.argv).execute()
            except:
                sys.exit(1)
        case 'debug-on':
            cli.DebugOn().execute()
        case 'debug-off':
            cli.DebugOff().execute()
        case other:
            print(f'ods: unknown command: {sys.argv[1]}')