#!/home/cakers/Software/anaconda3/envs/onedrive-sync/bin/python

from OneDriveCLI import OneDriveCLI
import logging
import sys

# App/Client ID: 9806a116-6f7d-4154-a06e-0c887dd51eed
# Tenant ID: 42a7cc42-d023-4e93-898d-3777ba423ebe

if __name__ == '__main__':
    logging.basicConfig()
    odc = OneDriveCLI()

    if sys.argv[1] == 'init':
        odc.initialise()
        print('OneDrive CLI for Linux initialised')
        sys.exit(0)

    if not odc.is_initialised():
        print('initialisation has not been run, please run "ods init" first')
        sys.exit(1)

    match(sys.argv[1]):
        case 'cd':
            print(odc.cd(sys.argv[2] if len(sys.argv) > 2 else '/'))
        case 'ls':
            print(odc.ls())
        case 'pwd':
            print(odc.pwd())
        case 'get':
            odc.get(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else './')
        case 'put':
            odc.put(sys.argv[2], sys.argv[3])
        case 'debug-on':
            odc.debug_on(True)
        case 'debug-off':
            odc.debug_on(False)
        case other:
            print(f'ods: unknown command: {sys.argv[1]}')