#!/home/cakers/Software/anaconda3/envs/onedrive-sync/bin/python

from OneDriveSynch import OneDriveSynch
import logging
import sys

# App/Client ID: 9806a116-6f7d-4154-a06e-0c887dd51eed
# Tenant ID: 42a7cc42-d023-4e93-898d-3777ba423ebe

if __name__ == '__main__':
    logging.basicConfig()
    logging.getLogger().setLevel(logging.DEBUG)
    ods = OneDriveSynch()

    if sys.argv[1] == 'init':
        ods.initialise()

    if not ods.is_initialised():
        print('initialisation has not been run, please run "ods init" first')
        sys,exit(1)

    match(sys.argv[1]):
        case 'cd':
            print(ods.cd(sys.argv[2] if len(sys.argv) > 2 else '/'))
        case 'ls':
            print(ods.ls())
        case 'pwd':
            print(ods.pwd())
        case 'get':
            ods.get(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else '')
        case other:
            print(f'ods: unknown command: {sys.argv[1]}')